# docker-compose.yml
version: "3.8"
services:
  bot:
    build: .
    env_file: .env
    depends_on: [db]
    ports:
      - "8080:8080"
    command: python -m bot.app.main
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
